### ISSUE TITLE
ServerSideCrashWhenfightBabyPigmanNearPortal

### ISSUE THREAD

**Issue by CatAndHorse** [Furgl/BabyMobs#12]
Time: 7/26/17 1:09 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.Entity.func_184191_r(Entity.java:2311)
	at furgl.babyMobs.common.entity.ai.EntityAIBabyHurtByTarget.func_75249_e(EntityAIBabyHurtByTarget.java:98)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:760)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2343)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2163)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at furgl.babyMobs.common.entity.monster.EntityBabyPigZombie.func_70071_h_(EntityBabyPigZombie.java:60)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2012)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2473)
	at net.minecraft.world.World.func_72866_a(World.java:1971)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)

**Comment by Furgl** [comment]
Could you please provide more information about the crash:
- Please provide the full crash log
- What MC, Baby Mobs, and Forge versions were you using?
- What exactly happened before the crash?
- Are you able to reproduce the crash?

**Comment by Furgl** [comment]
Closed until further information/confirmation provided.
