### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by LemADEC** [Furgl/BabyMobs#2]
We've had server crash related to babyMobs:

```
java.lang.NullPointerException: Ticking entity
        at net.minecraft.potion.PotionUtils.func_185181_a(SourceFile:90)
        at net.minecraft.entity.projectile.EntityTippedArrow.func_184558_a(EntityTippedArrow.java:74)
        at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70645_a(EntityBabySkeleton.java:67)
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
        at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
        at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70097_a(EntityBabySkeleton.java:119)
        at net.minecraft.entity.Entity.func_70030_z(Entity.java:458)
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216)
        at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1938)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
        at net.minecraft.world.World.func_72866_a(World.java:1964)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:1934)
        at net.minecraft.world.World.func_72939_s(World.java:1750)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)
```

This is with version 1.10.2-1.5.

**Comment by Furgl** [comment]
Thank you for bringing this to my attention. This is now fixed in v1.5.1:
[BabyMobs-1.10.2-1.5.1.jar.zip](https://github.com/Furgl/BabyMobs/files/486347/BabyMobs-1.10.2-1.5.1.jar.zip)
