### ISSUE TITLE
1.10.2 console spamming

### ISSUE THREAD

**Issue by Kehaan** [Furgl/BabyMobs#3]
Hello

The mod seems to be working ok, but the console is spamming a lot with:
<details><summary>Console Spam</summary>
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: java.lang.NoSuchMethodException: net.minecraft.entity.projectile.EntityTippedArrow.getArrowStack()
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at java.lang.Class.getDeclaredMethod(Class.java:2130)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70645_a(EntityBabySkeleton.java:71)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70097_a(EntityBabySkeleton.java:122)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.Entity.func_70098_U(Entity.java:1848)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2293)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntitySkeleton.func_70098_U(SourceFile:189)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72866_a(World.java:1960)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72870_g(World.java:1934)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72866_a(World.java:2024)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72870_g(World.java:1934)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72939_s(World.java:1750)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:18:31] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at java.lang.Thread.run(Thread.java:745)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: java.lang.NoSuchMethodException: net.minecraft.entity.projectile.EntityTippedArrow.getArrowStack()
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at java.lang.Class.getDeclaredMethod(Class.java:2130)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70645_a(EntityBabySkeleton.java:71)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70097_a(EntityBabySkeleton.java:122)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:273)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72866_a(World.java:1964)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72870_g(World.java:1934)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72939_s(World.java:1750)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:27:52] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at java.lang.Thread.run(Thread.java:745)
[14:33:24] [Server thread/INFO]  [Levels]: Level: 1
[14:34:00] [Server thread/INFO]  [Levels]: Level: 3
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: java.lang.NoSuchMethodException: net.minecraft.entity.projectile.EntityTippedArrow.getArrowStack()
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at java.lang.Class.getDeclaredMethod(Class.java:2130)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70645_a(EntityBabySkeleton.java:71)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:970)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at furgl.babyMobs.common.entity.monster.EntityBabySkeleton.func_70097_a(EntityBabySkeleton.java:122)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.Entity.func_70030_z(Entity.java:458)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72866_a(World.java:1964)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72870_g(World.java:1934)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.World.func_72939_s(World.java:1750)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:37:41] [Server thread/INFO] [STDERR]: [furgl.babyMobs.common.entity.monster.EntityBabySkeleton:func_70645_a:76]: at java.lang.Thread.run(Thread.java:745)
</details>

Do you need any logs ? Or is it a known issue?

- Kehaan

**Comment by Furgl** [comment]
Thank you for reporting this!

This has been fixed in v1.5.2: [BabyMobs-1.10.2-1.5.2.jar.zip](https://github.com/Furgl/BabyMobs/files/621082/BabyMobs-1.10.2-1.5.2.jar.zip)

**Comment by Kehaan** [comment]
Thank you very much <3
